name: profile_page
description: "A new Flutter package for profile page."
version: 0.0.2
homepage: https://github.com/KhaingZawLinn1998/profile_page.git

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  image_cropper: ^5.0.1
  image_picker: ^1.0.7
  zoom_widget: ^2.0.1
  page_transition: ^2.0.9
  loading_animation_widget: ^1.2.0+4
  cached_network_image: ^3.2.3
  image: ^4.2.0
  intl_phone_field: ^3.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: